version: '3.8'

services:
  # MongoDB (공통 데이터베이스)
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - D:\eventdb\data:/data/db
      - D:\eventdb\logs:/var/log/mongodb
    networks:
      - awana-network
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    command: mongod --logpath /var/log/mongodb/mongod.log --logappend

  # Event Service
  event-service:
    build: ./services/event-service
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_EVENT_DB}?authSource=${MONGO_AUTH_DB}
      - PORT=3001
      - NODE_ENV=production
    depends_on:
      - mongodb
    networks:
      - awana-network
    restart: unless-stopped

  # Church Service
  church-service:
    build: ./services/church-service
    ports:
      - "3002:3002"
    environment:
      - MONGODB_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_CHURCH_DB}?authSource=${MONGO_AUTH_DB}
      - PORT=3002
      - NODE_ENV=production
    depends_on:
      - mongodb
    networks:
      - awana-network
    restart: unless-stopped

  # Receipt Service
  receipt-service:
    build: ./services/receipt-service
    ports:
      - "3003:3003"
    environment:
      - MONGODB_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_RECEIPT_DB}?authSource=${MONGO_AUTH_DB}
      - PORT=3003
      - NODE_ENV=production
    depends_on:
      - mongodb
    networks:
      - awana-network
    restart: unless-stopped

  # Frontend Service (React)
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_EVENT_SERVICE_PORT=3001
      - NEXT_PUBLIC_CHURCH_SERVICE_PORT=3002
      - NEXT_PUBLIC_RECEIPT_SERVICE_PORT=3003
    depends_on:
      - event-service
      - church-service
      - receipt-service
    networks:
      - awana-network
    restart: unless-stopped

volumes:
  # 윈도우 경로 사용
  mongodb_data:
    driver: local

networks:
  awana-network:
    driver: bridge 
