version: '3.8'

services:
  # MongoDB (공통 데이터베이스)
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - D:\eventdb\data:/data/db
      - D:\eventdb\logs:/var/log/mongodb
      - D:\eventdb\backup:/data/backup
    networks:
      - awana-network
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    command: mongod --logpath /var/log/mongodb/mongod.log --logappend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # MySQL (TNT Camp 데이터베이스)
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - D:\tntcampdb\mysql:/var/lib/mysql
      - D:\tntcampdb\init:/docker-entrypoint-initdb.d
      - D:\tntcampdb\backup:/backup
    networks:
      - awana-network
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  # Event Service
  event-service:
    build: ./services/event-service
    expose:
      - "3001"
    environment:
      - MONGODB_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_EVENT_DB}?authSource=${MONGO_AUTH_DB}
      - PORT=3001
      - NODE_ENV=production
    depends_on:
      - mongodb
    networks:
      - awana-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  # Church Service
  church-service:
    build: ./services/church-service
    expose:
      - "3002"
    environment:
      - MONGODB_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_CHURCH_DB}?authSource=${MONGO_AUTH_DB}
      - PORT=3002
      - NODE_ENV=production
    depends_on:
      - mongodb
    networks:
      - awana-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Receipt Service
  receipt-service:
    build: ./services/receipt-service
    expose:
      - "3003"
    environment:
      - MONGODB_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_RECEIPT_DB}?authSource=${MONGO_AUTH_DB}
      - PORT=3003
      - NODE_ENV=production
    depends_on:
      - mongodb
    networks:
      - awana-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # BT Service
  bt-service:
    build: ./backend/bt-service
    expose:
      - "3004"
    environment:
      - MONGODB_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_BT_DB}?authSource=${MONGO_AUTH_DB}
      - PORT=3004
      - NODE_ENV=production
    depends_on:
      - mongodb
    networks:
      - awana-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Frontend Service (React + Nginx with HTTPS and API Proxy)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - NODE_ENV=production
    ports:
      - "80:80"
      - "3000:443"
    volumes:
      - ./nginx-https-awanaevent-with-api-proxy.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/letsencrypt
      - ./ssl/www:/var/www/certbot
    environment:
      - NODE_ENV=production
    depends_on:
      - event-service
      - church-service
      - receipt-service
    networks:
      - awana-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # TNT Camp Backend Server
  tntcamp-backend:
    build: ./backend-server
    expose:
      - "8080"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${TNTCAMP_DB_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - PORT=8080
    volumes:
      - D:\tntcampdb\uploads:/app/uploads
      - D:\tntcampdb\logs:/app/logs
    depends_on:
      - mysql
    networks:
      - awana-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # TNT Camp Main App
  tntcamp-app:
    build: 
      context: ./frontend/english-camp-app
      dockerfile: Dockerfile
    expose:
      - "80"
    environment:
      - NODE_ENV=development
      - REACT_APP_BACKEND_HOST=https://awanaevent.com
      - FAST_REFRESH=false
      - GENERATE_SOURCEMAP=false
      - PUBLIC_URL=/tntcamp
    networks:
      - awana-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # TNT Camp Admin App
  tntcamp-admin:
    build: 
      context: ./frontend/english-camp-admin
      dockerfile: Dockerfile
    expose:
      - "80"
    environment:
      - NODE_ENV=development
      - REACT_APP_BACKEND_HOST=https://awanaevent.com
      - FAST_REFRESH=false
      - GENERATE_SOURCEMAP=false
      - PUBLIC_URL=/tntadmin
    networks:
      - awana-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


volumes:
  mongodb_data:
    driver: local

networks:
  awana-network:
    driver: bridge 
