version: '3.8'

services:
  # MongoDB (공통 데이터베이스)
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - awana-network

  # Event Service
  event-service:
    build: ./services/event-service
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/event-service
      - PORT=3001
      - NODE_ENV=development
    depends_on:
      - mongodb
    networks:
      - awana-network

  # Church Service
  church-service:
    build: ./services/church-service
    ports:
      - "3002:3002"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/church-service
      - PORT=3002
      - NODE_ENV=development
    depends_on:
      - mongodb
    networks:
      - awana-network

  # Receipt Service
  receipt-service:
    build: ./services/receipt-service
    ports:
      - "3003:3003"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/receipt-service
      - PORT=3003
      - NODE_ENV=development
    depends_on:
      - mongodb
    networks:
      - awana-network

  # BT Service
  bt-service:
    build: ./services/bt-service
    ports:
      - "3004:3004"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/bt-service
      - PORT=3004
      - NODE_ENV=development
    depends_on:
      - mongodb
    networks:
      - awana-network

  # BT Frontend App
  awana-bt-app:
    build: ./awana-bt-app
    ports:
      - "3005:80"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://bt-service:3004
    depends_on:
      - bt-service
    networks:
      - awana-network

volumes:
  mongodb_data:

networks:
  awana-network:
    driver: bridge
