version: '3.8'

services:
  church-service:
    build: .
    ports:
      - "3002:3002"
    environment:
      - MONGODB_URI=mongodb://localhost:27017/church-service
      - PORT=3002
      - NODE_ENV=development
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 