version: '3.8'

services:
  receipt-service:
    build: .
    ports:
      - "3003:3003"
    environment:
      - MONGODB_URI=mongodb://localhost:27017/receipt-service
      - PORT=3003
      - NODE_ENV=development
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 